name: Manual Workflow with Inputs and Outputs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      run_tests:
        description: 'Run integration tests?'
        required: true
        type: boolean
        default: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Target Env is ${{ inputs.environment }}"
